# Generated by Django 6.0.4 on 2026-04-16 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='String',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string_name', models.CharField(max_length=250)),
                ('type', models.CharField(choices=[('p', 'P'), ('w', 'W')], default='p', max_length=250)),
                ('scale', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=9, null=True)),
                ('gauge', models.DecimalField(decimal_places=2, max_digits=9)),
                ('tension', models.DecimalField(decimal_places=2, max_digits=9)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SetupStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setup_name', models.CharField(blank=True, null=True, unique=True)),
                ('instrument_type', models.CharField(choices=[('guitar', 'Guitar'), ('bass', 'Bass')], max_length=250)),
                ('total_strings', models.IntegerField()),
                ('scale_sength', models.DecimalField(decimal_places=2, max_digits=9)),
                ('is_multi_scale', models.BooleanField(db_default=True)),
                ('string_type', models.CharField(max_length=250)),
                ('selected_tuning', models.CharField(max_length=250)),
                ('total_tension', models.DecimalField(decimal_places=2, max_digits=9)),
                ('is_public', models.BooleanField(default=False)),
                ('is_varified', models.BooleanField(default=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('strings', models.ManyToManyField(related_name='strings', to='databases_models.string')),
            ],
        ),
    ]
