# Generated by Django 6.0.4 on 2026-04-18 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databases_models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setupstorage',
            name='category',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
